### ISSUE TITLE
Add CoC document

### ISSUE THREAD

**Issue by srigi** [webelement/webelement.sk#70]
This project should include Code-of-conduct document to explicitly express that it is open to diversity.

Thanks!

**Comment by bazo** [comment]
+1

**Comment by fprochazka** [comment]
![that post gave me cancer](https://cloud.githubusercontent.com/assets/158625/12532726/219c5f82-c21b-11e5-8160-92206cbef1c4.jpg)

**Comment by ujovlado** [comment]
@srigi Come on ... do you think this is really needed? Are you crazy? In my opinion, community here is very nice, kind and open and things like this don't fit very well here.

**Comment by bazo** [comment]
how can you call him crazy? it's offending. we need a CoC because of people like you. You should leave the project, you're making me feel not welcome here.

**Comment by fprochazka** [comment]
![oppresing logic](https://cloud.githubusercontent.com/assets/158625/12533261/88322254-c22a-11e5-9901-9420a3887a37.jpg)

**Comment by ujovlado** [comment]
So, I'm closing this trolling session. :kissing_closed_eyes: :trollface:
